---
title: "SafePaths SEIR Impact"
author: "Andrea Nuzzo"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: yes
    fig_caption: true
  html_document: default
---

```{r message=FALSE, include=FALSE}
library(deSolve)
library(tidyverse)
library(ggthemes)
library(RCurl)
library(lubridate)
```

# Intro
Scope of this model is to demonstrate the impact of contact tracing procedures to limit the spreading of infectious diseases during outbreaks.

# Current situation as of `r Sys.Date()`

```{r}
# US population based on census 
N = 329968629

JHU_Confirmed<- getURL('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv') %>% 
  read_csv() %>% 
  filter(`Country/Region`=='US') %>%
  gather(date, Infected, -`Province/State`, -`Country/Region`, -Lat, -Long) %>% 
  group_by(`Province/State`) %>% 
  mutate(date = mdy(date), 
         time_from_zero = date - min(date)) 

JHU_Recovered <- getURL('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv') %>% 
  read_csv() %>% 
  filter(`Country/Region`=='US') %>%
  gather(date, Recovered, -`Province/State`, -`Country/Region`, -Lat, -Long)%>% 
  group_by(`Province/State`) %>% 
  mutate(date = mdy(date), 
         time_from_zero = date - min(date))

JHU_Deaths <- getURL('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv') %>% 
  read_csv() %>% 
  filter(`Country/Region`=='US') %>%
  gather(date, Deaths, -`Province/State`, -`Country/Region`, -Lat, -Long) %>% 
  group_by(`Province/State`) %>% 
  mutate(date = mdy(date), 
         time_from_zero = date - min(date))

Current_scenario <- JHU_Confirmed %>% 
  group_by(date) %>% 
  summarize(Infected = sum(Infected)) %>% 
  full_join(JHU_Recovered %>% 
  group_by(date) %>% 
  summarize(Recovered = sum(Recovered)))%>% 
  full_join(JHU_Deaths %>% 
  group_by(date) %>% 
  summarize(Deaths = sum(Deaths))) %>% 
  ungroup%>% 
  mutate(time_from_zero = as.numeric(date - min(date)))

Current_scenario %>% 
  gather(Compartments, Cases, -date, -time_from_zero) %>% 
    mutate(perc = Cases/N) %>% 
    ggplot(aes(x=time_from_zero, y=perc, color=Compartments)) +
    # ylim(c(0,1.1))+
    geom_point()+
    theme_clean()+
    scale_color_manual(values = c(Infected = 'red', 
                                  Recovered = 'green', 
                                  Deaths = 'black')) 

Infected_symptomatic = tail(Current_scenario, 1)$Infected
Recovered = tail(na.omit(Current_scenario), 1)$Recovered
Deaths = tail(Current_scenario, 1)$Deaths



```

# Preliminary model
Fitting a SIRD model on the current data

## Data and assumptions 

```{r echo=TRUE}

# Estimated parameters
R0 = 3.0 
contact_rate = 22 
infectious_period = 2.9
latent_period = 5.2
non_symptomatic_ratio = 0.6
case_to_fatality = 0.02
obs_time = 80

reference_date <- Sys.Date()-40

# Current state as JHU dashboard for `r Sys.Date()`

Infected = Current_scenario[Current_scenario$date>as.Date('2020-02-21'),]$Infected[1]
Recovered = Current_scenario[Current_scenario$date>as.Date('2020-02-21'),]$Recovered[1]
Deaths= Current_scenario[Current_scenario$date>as.Date('2020-02-21'),]$Deaths[1]

Susceptible = N - Current_scenario[Current_scenario$date>as.Date('2020-02-21'),]$Infected[1]

timepoints = seq(0, obs_time, by = .5)
```
##
```{r}
SIRD <- function(time, state, parameters) {
  par <- as.list(c(state, parameters))
  
  S=state[1]
  I=state[2]
  R=state[3]
  D=state[4]
  
  with(par, {
    dS <- -beta_value * (I/N) * S
    dI <- beta_value * (I/N) * S - gamma_value * I - mu_value * I
    dR <- gamma_value * I
    dD <- mu_value * I
    list(c(dS, dI, dR, dD))
  })
}


init <- c(Susceptible = Susceptible, 
          Infected = Infected, 
          Recovered= Recovered,
          Deaths = Deaths)

RSS <- function(parameters) {
  names(parameters) <- c("beta_value", "gamma_value", 'mu_value')
  out <- ode(y = init, 
             times = seq(1,dim(Current_scenario[Current_scenario$date>reference_date,])[1]), 
             func = SIRD, 
             parms = parameters)
  fit <- out[, 3]
  sum((Current_scenario[Current_scenario$date>reference_date,]$Infected - fit)^2)
}

Opt <- optim(par = c(R0/contact_rate, 1/infectious_period, 0.01), RSS, method = "L-BFGS-B", lower = c(0, 0, 0), upper = c(2, .05, .02))

Opt_par <- setNames(Opt$par, c("beta_value", "gamma_value", 'mu_value'))

R0_est <- with(as.list(Opt_par), beta_value/(gamma_value + mu_value))

fitted_cumulative_incidence <- data.frame(ode(y = init, times = seq(28,80), func = SIRD, parms = Opt_par))

fitted_cumulative_incidence%>% 
  as.data.frame()%>%
  gather(Compartments, perc, -time) %>% 
  ggplot(aes(x=time, y=perc, color=Compartments))+
  ylim(c(0,100000))+
  geom_line()+
  geom_point(data = Current_scenario %>% 
               gather(Compartments, perc, -time_from_zero, -date) %>% 
               rename(time=time_from_zero))

```

## Model

```{r}
SESQIRD <- function(current_timepoint, state_values, parameters){
  
  ## create state valriables
  S  = state_values[1] # susceptibles
  E  = state_values[2] # exposed
  SQ = state_values[3] # self-quarantined contacts
  Is = state_values[4] # infected symptomatic
  R  = state_values[5] # recovered
  D  = state_values[6] # recovered
  
  with(
    as.list(parameters), 
    {
      ## compute derivatives
      dS = (-beta_value/N) * S * Is
      dE = (beta_value/N) * S * Is - (delta_value * E) - (perc_app * E *Is) 
      dSQ = perc_app * E * Is  - delta_value * SQ
      dI = (delta_value * E) - (gamma_value * Is) + delta_value * SQ
      dR = (gamma_value * Is) - (mu_value * Is)
      dD = (mu_value * Is)
      
      # combine 
      results = c(dS, dE,dSQ, dI, dR, dD)
      list(results)
    }
  )
  
}

state_values <- c(Susceptible = Susceptible, 
                  Exposed = Infected * contact_rate,
                  Self_Isolated = 1,
                  Infected = Infected, 
                  Recovered= Recovered,
                  Deaths = Deaths)

```

```{r}
res <- tibble()

for (percent_adoption in seq(0.0, 0.99, by=.1)) {
  test_params = c(
        Opt_par[1]*(1-percent_adoption),
        Opt_par[2],
        Opt_par[3],
        delta_value = 1/latent_period,
        perc_app = percent_adoption
      )
  
  out <- lsoda(y = state_values, times = seq(28,300), func = SESQIRD, parms = test_params)

  out <- out %>% 
    as.data.frame()
  
  p <- out %>% 
    gather(Compartments, perc, -time) %>% 
    ggplot(aes(x=time, y=perc, color=Compartments)) +
    # ylim(c(0,1e7))+
    geom_line()+
    theme_clean()+
    scale_color_manual(values = c(Susceptible = 'grey',
                                  Exposed = 'brown',
                                  Self_Isolated = 'orange',
                                  Infected = 'red',
                                  Recovered = 'green',
                                  Deaths = 'black')) +
    labs(title=paste0("SESQIRD model, ", percent_adoption*100, "% adoption rate"),
         subtitle=paste0('Rt = ', round(with(as.list(test_params), beta_value/(gamma_value+mu_value)), 2))
    )
  
  print(p)
    
    res <- res %>%  
      bind_rows(out %>% mutate(adoption=percent_adoption))
    
}
```


```{r}
res %>% 
  # mutate_at(vars(S,E,Is,R,D), ~.*N) %>%
  gather(Compartments, value, -time, -adoption) %>%  
  ggplot()+
  aes(x=time, color=Compartments, fill=Compartments, y=value) +
  geom_bar(stat = 'identity') +
  facet_grid(Compartments~adoption)+
  theme_tufte()+
  theme(axis.text.x = element_text(angle = 90),
        legend.position = 'right')+
  scale_fill_colorblind()+
  scale_color_colorblind()
  
```
```{r results='html'}
library(knitr)
library(kableExtra)
res %>%
  group_by(adoption) %>% 
  arrange(desc(adoption)) %>% 
  summarize_all(~max(.)) %>% 
  select(adoption, max_infected = Infected, max_death=Deaths) %>% 
  kable("latex", booktabs = T, 
        caption = 'Estimated decrease of peak disease impact indicators, regardless of time. Model assumes 100% efficacy of self-isolation') %>%
  kable_styling(latex_options = "striped", bootstrap_options = c("condensed")) 
```

